name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Ensure Android SDK directory exists
      run: mkdir -p $HOME/Android/Sdk

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create local.properties
      run: echo "sdk.dir=$HOME/Android/Sdk" > local.properties
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Cache Gradle
      id: cache-gradle
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: gradle-${{ hashFiles('**/build.gradle', '**/settings.gradle') }}
        restore-keys: |
          gradle-

    - name: Compile and run tests on robot code
      run: ./gradlew build

    - name: Upload Lint Results
      uses: actions/upload-artifact@v4
      with:
        name: lint-results
        path: TeamCode/build/reports/lint-results-debug.html
