name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Accept Android SDK license
      run: yes | ~/Android/Sdk/tools/bin/sdkmanager --licenses
      
    - name: Compile and run tests on robot code
      run: ./gradlew build

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      with:
        name: Reports
        path: TeamCode/build/reports/
